services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb_user
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - data-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:${DB_PORT}/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: redis:latest
    container_name: redis_coledzh-store
    ports:
      - ${REDIS_PORT}:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
      REDIS_DB: ${REDIS_DB}
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  data-volume:
  redis: