// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package register

import (
	"context"

	"github.com/AlexMickh/twitch-clone/internal/dtos"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegisterer creates a new instance of MockRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterer {
	mock := &MockRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegisterer is an autogenerated mock type for the Registerer type
type MockRegisterer struct {
	mock.Mock
}

type MockRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterer) EXPECT() *MockRegisterer_Expecter {
	return &MockRegisterer_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockRegisterer
func (_mock *MockRegisterer) Register(ctx context.Context, req dtos.RegisterRequest) (string, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.RegisterRequest) (string, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.RegisterRequest) string); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dtos.RegisterRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegisterer_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegisterer_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req dtos.RegisterRequest
func (_e *MockRegisterer_Expecter) Register(ctx interface{}, req interface{}) *MockRegisterer_Register_Call {
	return &MockRegisterer_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockRegisterer_Register_Call) Run(run func(ctx context.Context, req dtos.RegisterRequest)) *MockRegisterer_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(dtos.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegisterer_Register_Call) Return(s string, err error) *MockRegisterer_Register_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRegisterer_Register_Call) RunAndReturn(run func(ctx context.Context, req dtos.RegisterRequest) (string, error)) *MockRegisterer_Register_Call {
	_c.Call.Return(run)
	return _c
}
