// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package login

import (
	"context"

	"github.com/AlexMickh/twitch-clone/internal/dtos"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoginer creates a new instance of MockLoginer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginer {
	mock := &MockLoginer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginer is an autogenerated mock type for the Loginer type
type MockLoginer struct {
	mock.Mock
}

type MockLoginer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginer) EXPECT() *MockLoginer_Expecter {
	return &MockLoginer_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockLoginer
func (_mock *MockLoginer) Login(ctx context.Context, req dtos.LoginRequest, userAgent string) (string, error) {
	ret := _mock.Called(ctx, req, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.LoginRequest, string) (string, error)); ok {
		return returnFunc(ctx, req, userAgent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dtos.LoginRequest, string) string); ok {
		r0 = returnFunc(ctx, req, userAgent)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dtos.LoginRequest, string) error); ok {
		r1 = returnFunc(ctx, req, userAgent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginer_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockLoginer_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req dtos.LoginRequest
//   - userAgent string
func (_e *MockLoginer_Expecter) Login(ctx interface{}, req interface{}, userAgent interface{}) *MockLoginer_Login_Call {
	return &MockLoginer_Login_Call{Call: _e.mock.On("Login", ctx, req, userAgent)}
}

func (_c *MockLoginer_Login_Call) Run(run func(ctx context.Context, req dtos.LoginRequest, userAgent string)) *MockLoginer_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dtos.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(dtos.LoginRequest)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoginer_Login_Call) Return(s string, err error) *MockLoginer_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLoginer_Login_Call) RunAndReturn(run func(ctx context.Context, req dtos.LoginRequest, userAgent string) (string, error)) *MockLoginer_Login_Call {
	_c.Call.Return(run)
	return _c
}
