name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1' # Specify your desired Go version
          cache: true # Enable caching for Go modules

      - name: Download Go modules
        run: go mod download

      - name: build
        run: docker build -t twitch-clone:latest .

      - name: lint
        run: golangci-lint run ./...
        
      - name: test
        run: CI=true go test -v -race ./...